// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Kahoot.Repository.Models;

public partial class Participant
{
    public int ParticipantId { get; set; }

    public int SessionId { get; set; }

    public int UserId { get; set; }

    public string Team { get; set; }

    public int? Score { get; set; }

    public DateTime JoinAt { get; set; }

    public virtual ICollection<Response> Responses { get; set; } = new List<Response>();

    public virtual QuizSession Session { get; set; }

    public virtual User User { get; set; }
}