// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Kahoot.Repository.Models;

public partial class Quiz
{
    public int QuizId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Visibility { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual User CreateByNavigation { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<QuizSession> QuizSessions { get; set; } = new List<QuizSession>();
}