// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Kahoot.Repository.Models;

public partial class QuizSession
{
    public int SessionId { get; set; }

    public int QuizId { get; set; }

    public int HostId { get; set; }

    public string CodeRoom { get; set; }

    public DateTime? StartTime { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? EndTime { get; set; }

    public int? CurrentQuestionIndex { get; set; }

    public int? TotalQuestion { get; set; }

    public int? TotalScore { get; set; }

    public virtual User Host { get; set; }

    public virtual ICollection<Participant> Participants { get; set; } = new List<Participant>();

    public virtual ICollection<QuestionSession> QuestionSessions { get; set; } = new List<QuestionSession>();

    public virtual Quiz Quiz { get; set; }
}