// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Kahoot.Repository.Models;

public partial class Response
{
    public int ResponseId { get; set; }

    public int ParticipantId { get; set; }

    public int QuestionSessionId { get; set; }

    public bool IsCorrect { get; set; }

    public DateTime? AnsweredAt { get; set; }

    public virtual Participant Participant { get; set; }

    public virtual QuestionSession QuestionSession { get; set; }
}