// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Kahoot.Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Participant> Participants { get; set; } = new List<Participant>();

    public virtual ICollection<QuizSession> QuizSessions { get; set; } = new List<QuizSession>();

    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();
}